server:
   port: 9296

spring:
  application:
      name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vktyagi/microservices.git
          clone-on-start: true


  profiles:
    active: qa


